from django.db import models

# Create your models here.


class Student(models.Model):
    # id = models.AutoField()  # this field is automatically generated by the Django
    name = models.CharField(max_length=100)
    age = models.IntegerField()
    email = models.EmailField(null=True, blank=True)
    address = models.TextField(null=True, blank=True)
    # image = models.ImageField()  # to use this field, install Pillow
    # file = models.FileField()


# class Product(models.Model):
#     pass


class Car(models.Model):
    car_name = models.CharField(max_length=100)
    speed = models.IntegerField(default=50)
